[tool.poetry]
name = "my tests"
version = "0.1.0"
description = "my tests"
authors = ["fzoo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
